# Generated by Django 3.2.5 on 2021-07-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20210719_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
