# Generated by Django 3.2.5 on 2021-07-19 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=130, verbose_name='Email')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('url', models.URLField(blank=True, db_index=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
